name: Get Subscription Daily

on:
  schedule:
    - cron: '0 0 * * *'  # 每天凌晨（UTC 时间）执行
  workflow_dispatch: # 允许手动触发

permissions:
  contents: write

jobs:
  execute-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install pyYAML
      run: pip3 install pyYAML

    - name: Install other dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Collect Subscribe
      id: collect
      run: |
        cd aggregate
        python -u subscribe/collect.py -skip

    - name: Create/Update Gist
      env:
        GH_TOKEN: ${{ secrets.PRIVATE_TOKEN_AGGREGATOR }}
      run: |
        cd aggregate
        gh gist edit ${{ secrets.GIST_ID }} --add "proxies.yaml"
